version: '3.7'

services:
  mango.services.shoppingcartapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8002:80" 
      - "8003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - shoppingcart-db

  shoppingcart-db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${sapassword}
    ports:
      - "1433:1433"

  mango.services.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80" 
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identity-db

  identity-db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${sapassword}
    ports:
      - "5432:5432"

  mango.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8004:80" 
      - "8005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mango.services.identity
      - mango.services.shoppingcartapi
